### ISSUE TITLE
Opening a stream in both sides makes one of them send a RST_STREAM and throw

### ISSUE THREAD

**Issue by diasdavid** [indutny/spdy-transport#10]
Wrote one more test on `abstract-stream-muxer` to identify a bug I was getting in `ipfs-swarm`, it seems that in 1.0.0-rc7, when we attempt to open a stream in both sides, one of them throws

test: https://github.com/diasdavid/abstract-stream-muxer/blob/master/tests/base-test.js#L51-L81
To run it using spdy-transport, git clone this repo https://github.com/diasdavid/node-spdy-stream-muxer, install deps and `npm test`.

I'm using 1.0.0-rc7 because of this issue: https://github.com/indutny/spdy-transport/issues/9

**Comment by indutny** [comment]
Arrgh, thanks! I missed that thing

**Comment by indutny** [comment]
Fixed in 3c64cd6. Thanks!

**Comment by diasdavid** [comment]
Awesome! Thank you :)
