### ISSUE TITLE
A dialer connection/endpoint can dial streams to a dialer connection/endpoint, it only throws (RST_STREAM) when the second dialer tries to dial back

### ISSUE THREAD

**Issue by diasdavid** [indutny/spdy-transport#12]
I found (by my mistake in putting the wrong bool on 'isServer') that a spdy-transport `client` can dial a stream through a socket that has a `client` in the other side without throwing any errors, however, if the dialer in the other side (which should be in fact a listener/server), tries to dial back a stream, we receive a RST_STREAM. Probably because it tries to use the same STREAM_ID and that is when it understand that both endpoints are dialers?

**Comment by indutny** [comment]
Yeah, sides should be different. One should be server and the other should be client.

**Comment by diasdavid** [comment]
Right, but shouldn't there be an error when a 'spdy-client' gets a SYN_STREAM with a odd stream Id? Maybe PROTOCOL_ERROR or REFUSED_STREAM? It took me a bunch of ours (and a lot of tests and experimentations which always worked, excepted in my main code), why the listener (or so I thought it was), was error'ing on stream creation with RST_STREAM, specially after the dialer had already opened a bunch of stream to it

**Comment by indutny** [comment]
Fixed in f390245, thanks!
