### ISSUE TITLE
stream.destroy()

### ISSUE THREAD

**Issue by diasdavid** [indutny/spdy-transport#15]
@mafintosh just asked me in IRC about a way to "blow up" a spdy stream. Context:

> 23:59 <@mafintosh> daviddias: we need a way to blow up the stream
23:59 <@mafintosh> in case of errors etc
23:59 <@mafintosh> daviddias: its usually implemented with stream.destroy() in node

I couldn't find any method on streams.js for `destroy`, nor in tests, is there something implemented I'm missing?

**Comment by indutny** [comment]
Have you tried `.abort()`? :)

**Comment by diasdavid** [comment]
That's the one, thank you :)

**Comment by indutny** [comment]
No problem.
