### ISSUE TITLE
SPDY compression pool

### ISSUE THREAD

**Issue by diasdavid** [indutny/spdy-transport#2]
@indutny does creating a spdy compression pool require an extra option? Other than:
https://github.com/diasdavid/spdy-transport/blob/spdy-parser-tests/test/spdy/parser-test.js#L10-L13

Getting this err:

```
  1) SPDY Parser "before each" hook:
     TypeError: Cannot read property 'length' of undefined
      at Pool.get (lib/spdy-transport/protocol/spdy/zlib-pool.js:43:25)
      at Context.<anonymous> (test/spdy/parser-test.js:12:21)
```

**Comment by indutny** [comment]
Yeah, it needs a `version` argument: https://github.com/indutny/spdy-transport/blob/master/lib/spdy-transport/protocol/spdy/zlib-pool.js#L42

**Comment by diasdavid** [comment]
Thank you :) Any special reason why have 3 empty arrays tagged with different versions?

Also, could you enlighten me on what skipPreface really is? I see it is implemented on http2 but not in spdy:
https://github.com/indutny/spdy-transport/blob/master/lib/spdy-transport/protocol/http2/parser.js#L37-L44
https://github.com/indutny/spdy-transport/blob/master/lib/spdy-transport/protocol/spdy/parser.js#L32-L34

Right now I'm trying to get at least one test to work, but unfortunately it never outputs the frame:
https://github.com/diasdavid/spdy-transport/blob/spdy-parser-tests/test/spdy/parser-test.js#L54-L66
It executes de callback though, but with empty error.

Using node debug I see that it reaches https://github.com/indutny/spdy-transport/blob/master/lib/spdy-transport/protocol/spdy/parser.js#L57 even.

**Comment by indutny** [comment]
Yes, three different versions for possibly three different zlib dictionaries. Each pools the zlib instances, because they are expensive to create and are easy to reuse.

HTTP2 has a PREFACE, which is sometimes optional. If you do not want to expect it, and you most likely don't if you are not running real HTTP2 server - you should call `.skipPreface()` and parser won't wait for it.

**Comment by diasdavid** [comment]
Right, since this is supposed to be running on a server that has to support several client impl, it requires the 3 pools (In my head I was thinking of only supporting at max one impl at a time), got it, thanks :)

Another question when it comes to tests, wondering if you have any trick to generate all of those http2 hex frames available in the tests. Just sniffed some (thought it would be the easier way, the wire doesn't lie :) ), but when converting it to hex and passing it to the parser.js, it doesn't output the frame as expected. Wondering what am I missing. Probably some endianness'schisms. Thoughts?

**Comment by indutny** [comment]
@diasdavid I'd use HEX frames, because later we will verify framer by just using parser. The way I did it for HTTP2 - was just packet sniffing.

What kind of problems do you have, and with what frames?
