### ISSUE TITLE
Firefox H2 connection reset

### ISSUE THREAD

**Issue by utvara** [indutny/spdy-transport#25]
Hi, I'm having problems with spdy since today. 

I'm using spdy v3.0.0 package. I was not able to isolate the problem in short time, but only difference I can see is the upgrade of the spdy-transport (it got automatic update from 2.0.4 to 2.0.5 during install of spdy). 

I'm sorry I don't have better information at this point, I'll try to provide more info in next couple of days. I can confirm that Chrome, Safari and IE are working ok.  

Firefox error:
```
Secure Connection Failed

The connection to the server was reset while the page was loading.

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

**Comment by indutny** [comment]
Yikes! :)

I think I will need more details on this, how to reproduce and stuff like that.

Thank you very much!

**Comment by indutny** [comment]
Actually, fixed! :)

**Comment by utvara** [comment]
Wow, that was fast :+1:
