### ISSUE TITLE
Client setting SETTINGS_HEADER_TABLE_SIZE causes connection reset in Chrome 55.0.2853.0 dev

### ISSUE THREAD

**Issue by apapirovski** [indutny/spdy-transport#29]
Wasn't sure whether to open this here on in hpack.js, as I don't know enough about the topic.

See the discussion in the [Chromium tracker](https://bugs.chromium.org/p/chromium/issues/detail?id=644031&q=hsts&colspec=ID%20Pri%20M%20Stars%20ReleaseBlock%20Component%20Status%20Owner%20Summary%20OS%20Modified).

The offending code seems to be here:

- https://github.com/indutny/spdy-transport/blob/aa2d889f7b49d6f6b52ed6979fcb236f6662eb39/lib/spdy-transport/protocol/http2/hpack-pool.js#L19
- https://github.com/indutny/hpack.js/blob/7338b7ec5c2fc3c234bbf56d1e570925c15d32a1/lib/hpack/table.js#L82

And the spec says:

> SETTINGS_HEADER_TABLE_SIZE (0x1): Allows the sender to inform the remote endpoint of the maximum size of the header compression table used to decode header blocks, in octets. The encoder can select any size equal to or less than this value by using signaling specific to the header compression format inside a header block (see [COMPRESSION]). The initial value is 4,096 octets.

The fact that maxSize also sets maxProtocolSize seems to break things.

**Comment by indutny** [comment]
Yikes! That's terrible.

Thank you for reporting this. I'll take a look.

**Comment by indutny** [comment]
Thank you! It should be fixed now.

**Comment by indutny** [comment]
Sorry for a delay.
