### ISSUE TITLE
HTTP/2 handling of unsupported headers

### ISSUE THREAD

**Issue by pavel** [indutny/spdy-transport#33]
As per HTTP/2 spec some headers are forbidden:

> An HTTP/2.0 request or response MUST NOT include any of the following header fields:
> Connection, Host, Keep-Alive, Proxy-Connection, Transfer-Encoding, and Upgrade

Is this somehow handled in this library?

**Comment by indutny** [comment]
Host and Connection are in: https://github.com/indutny/spdy-transport/blob/3a31e7c2145bb4711ee09736829cb73e399e6723/lib/spdy-transport/protocol/http2/framer.js#L145-L150 . I guess we can handle the rest too.

Would you care to submit a PR for this?

Thanks for reporting it!

**Comment by pavel** [comment]
@mykiimike @indutny As far as I understand this is a webkit-browser specific issue. Chrome also drops connections if any of not allowed headers are returned in response.

@indutny There's a PR by @mykiimike #35.

**Comment by pavel** [comment]
Resolved by PR #35.
