### ISSUE TITLE
H2 Protocol on iOS device

### ISSUE THREAD

**Issue by mykiimike** [indutny/spdy-transport#34]
Hi there,

Hope you well. I just take a tour on issues to match my problem and maybe the #33 and #22 are linked.
I am unable to connect to my app using H2 protocol. The connection stales and dies after couple of minutes.
When i remove H2 from protocols list then my app works.

If you have any idea.

Michael

**Comment by mykiimike** [comment]
Okay i made a test and apparently the problem comes with the headers filtering as shown in #33

**Comment by mykiimike** [comment]
For information it breaks (at least):
* com.apple.Safari.WebFeedParser/602.1.44 CFNetwork/808.0.2 Darwin/16.0.0
* Mozilla/5.0 (Macintosh; Intel Mac OS X 10_12) AppleWebKit/602.1.50 (KHTML, like Gecko) Version/10.0 Safari/602.1.50

**Comment by pavel** [comment]
Can be closed. See PR #35.
