### ISSUE TITLE
Is there a simple way to disable frame chunking? 

### ISSUE THREAD

**Issue by diasdavid** [indutny/spdy-transport#37]

**Comment by indutny** [comment]
`maxChunk: false` connection option will do it.

**Comment by diasdavid** [comment]
Thank you! :)

**Comment by indutny** [comment]
@diasdavid hey David!

Completely unrelated to this, but I was curious if you may want or know anyone who may want to maintain both `spdy-transport` and `node-spdy`?

Asking you first, because of your numerous contributions and discussions that we had together. You are very competent person, and I feel that in your hands project may continue to live and evolve again.

Nevertheless, I realize that it is quite a lot of pressure so please feel free to decline it if it does seem to be the right thing to do to you.

Thank you,
Fedor.

**Comment by diasdavid** [comment]
I'm really flattered by having your trust, thank you, Fedor :) 

I'm happy to maintain them and also, find more contributors that would like to help on the endeavour as well. Do you find yourself out of time nowadays due to other projects, or has the project outgrew the capacity of a single maintainer? 

I've been half following the developments of http2 in Node.js core, I'm not 100% if that means that node-spdy will become part of core, can you give me an update on that or point me to where to read more?

Please do brain dump everything that comes to mind about both modules, through this issue, another one, a gist or my [email](mail@daviddias.me) :)

**Comment by indutny** [comment]
It just totally outgrew my capacity, and honestly saying it did so long time ago.

http2 work done is core is happening independently of node-spdy development. Still I believe that we need this module for older Node.js version and for the sake of having JS-only solution to this.

Adding you to these repos. Thank you so much!

**Comment by indutny** [comment]
@diasdavid regarding the plans - I don't have any at this moment. There just some PRs and issues that are probably worth looking in all of these repos :wink:

**Comment by diasdavid** [comment]
What are your thoughts about moving the spdy modules into an organization? I've learned a lot from building the community around https://github.com/ipfs, https://github.com/libp2p, https://github.com/multiformats and https://github.com/ipld and some of the top things why it would be very helpful to me in this maintainer role are:

- Be able to have a [waffle board](https://waffle.io/indutny/node-spdy), without needing to ask you to set git hooks by hand. This waffle board will help me keep on track on issues, and digest them weekly
- Create an entry point for spdy/http2 enthusiasts 
- Make it easy to rail in new contributors by having more fine-grained management of 'teams' (unfortunately, github perms in user repos isn't that great).

Sounds good?

**Comment by indutny** [comment]
This sounds pretty good to me!

**Comment by diasdavid** [comment]
All right! Created the org https://github.com/spdy-http2 invited you, you need to be the one moving them, but then I should be able to do the rest :)

**Comment by indutny** [comment]
Moved everything over.
