### ISSUE TITLE
multi streams aka push streams

### ISSUE THREAD

**Issue by diasdavid** [indutny/spdy-transport#6]
I need some clarifications on the push streams API. Mainly, why is the stream object the interface to open more streams and not the client/server objects themselves?

e g
- 1 server: https://github.com/indutny/spdy-transport/blob/master/test/both/transport/push-test.js#L38-L47
- 2 client: https://github.com/indutny/spdy-transport/blob/master/test/both/transport/push-test.js#L52-L70

Does that mean that every 2nd or later stream is always a child to the first stream opened? Can't streams between a client and a server live in parallel? 

For example, the go impl offers a interface on the Connection interface to open 1-n streams without having to create nesting

**Comment by indutny** [comment]
I have important question for you :) Have you actually read the SPDY or HTTP2 spec?

The PUSH streams depend on some other streams, therefore they can't be created just by themselves. Regular streams however might be created using `connection.request`. You may create multiple streams, not just one.

Furthermore other side may reject any PUSH stream for whatever reason it thinking it should do it. Therefore PUSH streams are kind of optional part of the protocol.

**Comment by diasdavid** [comment]
I'm sorry @indutny, I sincerely had no intentions of being annoying to you or making lesser of your time, apologies for my inconvenience. Answering your question, I'm very familiar with with the SPDY, primarily the 3.1 spec after rereading countless times. As for the HTTP2 spec, I can't say I'm so proficient in it, but it is also not strange.

You are totally right, PUSH streams depend on other stream being open. What I want to be able to do, is after opening the socket between the two agents, to be able to open new streams both ways. To do this from the client side, we have `connection.request`, which I was hoping that it would also work from the server side (or through some other call).

I've trying to call `connection.request` from the server end, but unsuccessfully. Here is what my example of what I tried:
- https://github.com/diasdavid/spdy-cross-test/blob/master/node/server-multi.js
- https://github.com/diasdavid/spdy-cross-test/blob/master/node/client-multi.js

**Comment by indutny** [comment]
@diasdavid sorry if it sounded rude, you wasn't annoying at all. I was just trying to say that the spec has the better answer than I do.

As far as I see it, from the point of SPDY, it is not possible to send request from server. Only PUSH might be sent out of it.

The situation is a bit different for HTTP2, though. Which, btw, I'm not sure how to support... Asked @igrigorik about it on twitter. Right now I'm thinking about killing the stream if there is no `stream` listener on connection...

**Comment by jbenet** [comment]
/lurking

> As far as I see it, from the point of SPDY, it is not possible to send request from server. Only PUSH might be sent out of it.

No, it is possible to create streams from the server, in both SPDY and HTTP/2.

The SPDY 3.1 spec says (bold mine):

> ### [2.3.2 Stream creation](https://www.chromium.org/spdy/spdy-protocol/spdy-protocol-draft3-1#TOC-2.3.2-Stream-creation)
> 
> A stream is created by sending a control frame with the type set to SYN_STREAM (Section 2.6.1). **If the server is initiating the stream, the Stream-ID must be even.** If the client is initiating the stream, the Stream-ID must be odd. 0 is not a valid Stream-ID. Stream-IDs from each side of the connection must increase monotonically as new streams are created.

The HTTP/2 spec says (bold mine):

> ### [5.1 Stream States](https://http2.github.io/http2-spec/#StreamStates)
> 
> Both endpoints have a subjective view of the state of a stream that could be different when frames are in transit. **Endpoints do not coordinate the creation of streams; they are created unilaterally by either endpoint.** The negative consequences of a mismatch in states are limited to the "closed" state after sending RST_STREAM, where frames might be received for some time after closing.

So, in both SPDY and HTTP/2, _either side_ can open a stream. in SPDY it's with `SYN_STaREAM` frame, and in `HTTP/2` it's with `HEADERS` frame. 

For SPDY, libraries like [spdystream](https://github.com/docker/spdystream) reflect this with a very simple `CreateStream` available to either side.

**Comment by indutny** [comment]
Oh nice then! I guess spdy-transport already does this in a right way :) Thank you @jbenet!

**Comment by jbenet** [comment]
@indutny :+1:  

> I guess spdy-transport already does this in a right way :) 

hmmm but then what's wrong here?

> I've trying to call connection.request from the server end, but unsuccessfully. Here is what my example of what I tried:
> 
> - https://github.com/diasdavid/spdy-cross-test/blob/master/node/server-multi.js
> - https://github.com/diasdavid/spdy-cross-test/blob/master/node/client-multi.js

**Comment by diasdavid** [comment]
Very quick update: I've just done two more tests: 
- one with a setTimeout on the `server.request`, resulting in success
- other with the server.request on the callback from `transport.connection.create`, resulting in failure, but not err

**Comment by indutny** [comment]
@diasdavid @jbenet it is very odd that this is happening. There are almost no differences between server and client code. Most of the differences are debug logging prefix change :)

@diasdavid may I ask you to run failing example with `DEBUG="spdy:connection:*"` and gist the results?

**Comment by diasdavid** [comment]
Here you go:)

```
# server side
» DEBUG="spdy:connection:*" node server-multi.js                                                          
  spdy:connection:server id=0 add stream=2 +0ms
/Users/david/Documents/Code/ipfs/spdy-transport/lib/spdy-transport/protocol/spdy/framer.js:98
  this.compress.write(block.render(), callback);
               ^
TypeError: Cannot read property 'write' of null
    at Framer.headersToDict (/Users/david/Documents/Code/ipfs/spdy-transport/lib/spdy-transport/protocol/spdy/framer.js:98:16)
    at Framer._synFrame (/Users/david/Documents/Code/ipfs/spdy-transport/lib/spdy-transport/protocol/spdy/framer.js:176:8)
    at Framer.requestFrame (/Users/david/Documents/Code/ipfs/spdy-transport/lib/spdy-transport/protocol/spdy/framer.js:211:8)
    at Connection.request (/Users/david/Documents/Code/ipfs/spdy-transport/lib/spdy-transport/connection.js:511:26)
    at Server.<anonymous> (/Users/david/Documents/Code/go-projects/src/spdy-cross-test/node/server-multi.js:47:10)
    at Server.emit (events.js:107:17)
    at TCP.onconnection (net.js:1330:8)
```

```
# client side
» DEBUG="spdy:connection:*" node client-multi.js                                                         
  spdy:connection:client id=0 session window drain, update by -65280 +0ms
  spdy:connection:client id=0 add stream=1 +4ms
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: write EPIPE
    at exports._errnoException (util.js:746:11)
    at WriteWrap.afterWrite (net.js:775:14)
```

**Comment by igrigorik** [comment]
> You are totally right, PUSH streams depend on other stream being open. What I want to be able to do, is after opening the socket between the two agents, to be able to open new streams both ways. To do this from the client side, we have connection.request, which I was hoping that it would also work from the server side (or through some other call).

- The client can send new requests at any time without any restrictions. 
- The server requires an 'open parent stream' (a stream previously opened by the client and which is not yet closed) against which the push would happen, see: https://httpwg.github.io/specs/rfc7540.html#StreamStatesFigure

**Comment by indutny** [comment]
Aaah... I guess you may want to wait for `version` event on the server connection. This way it will detect the client SPDY version, and choose the right compression.

Alternatively, you may want to use `.start(3.1)` if you are sure about the other side's version and do not want to wait for the confirmation from other side.

Anyway, fixed the error message, should be more meaningful now. Thanks!

**Comment by indutny** [comment]
@igrigorik I think @jbenet is quite right in his statement above. PUSH streams indeed require parent stream, but there is no limitation to creating streams on both side (I mean just HEADERS, not PUSH_PROMISE).

@igrigorik on twitter you said that it would be a PROTOCOL_ERROR in chromium. Have I understood you well? If yes - why doesn't chromium reply with RST CANCEL instead?

I'm only starting the process of integrating it into node-spdy, so it is a bit hard to check it myself yet.

**Comment by igrigorik** [comment]
@indutny I was talking about h/2; the SPDY behavior may be different and we'll be deprecating it in early 2016 in Chrome.

**Comment by indutny** [comment]
@igrigorik hm... It is the same in HTTP2, right? The streams *may* be created by both sides, it is the other side who decided that it wants or do not wants the stream, not the protocol error.

**Comment by igrigorik** [comment]
Client can disable server push, or limit number of current streams (via SETTINGS).

Re, protocol error: I'm nitpicking.. The server needs to send a PUSH_PROMISE, which contains the header block, not a HEADERS frame when initiating push, and it needs a parent. Emitting a HEADERS from the server will cause a protocol error.

**Comment by indutny** [comment]
@igrigorik I'm not talking about PUSH streams :) What if server just wants to initiate a request from its side? Is there any place in spec that prohibits it?

**Comment by igrigorik** [comment]
> In the absence of more specific guidance elsewhere in this document, implementations SHOULD treat the receipt of a frame that is not expressly permitted in the description of a state as a connection error (Section 5.4.1) of type PROTOCOL_ERROR. Note that PRIORITY can be sent and received in any stream state. Frames of unknown types are ignored.

See: https://httpwg.github.io/specs/rfc7540.html#StreamsLayer.. So, yes, that's prohibited.

**Comment by indutny** [comment]
On one hand, on other:

```
All streams start in the "idle" state.

The following transitions are valid from this state:

Sending or receiving a HEADERS frame causes the stream to become "open". The stream identifier is selected as described in Section 5.1.1. The same HEADERS frame can also cause a stream to immediately become "half-closed".
Sending a PUSH_PROMISE frame on another stream reserves the idle stream that is identified for later use. The stream state for the reserved stream transitions to "reserved (local)".
Receiving a PUSH_PROMISE frame on another stream reserves an idle stream that is identified for later use. The stream state for the reserved stream transitions to "reserved (remote)".
Note that the PUSH_PROMISE frame is not sent on the idle stream but references the newly reserved stream in the Promised Stream ID field.
Receiving any frame other than HEADERS or PRIORITY on a stream in this state MUST be treated as a connection error (Section 5.4.1) of type PROTOCOL_ERROR.
```

All streams should be in `idle`, and so HTTP2 explicitly guides implementations to accept HEADERS for idle stream.

**Comment by diasdavid** [comment]
> Alternatively, you may want to use .start(3.1) if you are sure about the other side's version and do not want to wait for the confirmation from other side.

Woot! Nice, works perfectly now! :)

**Comment by igrigorik** [comment]
@indutny afaik, that's not allowed. The server must reserve a stream via push_promise, which itself must have a parent "client-initiated stream".

**Comment by indutny** [comment]
@igrigorik is there any way to submit this question to HTTP2 wg?

**Comment by igrigorik** [comment]
Yep: https://lists.w3.org/Archives/Public/ietf-http-wg/

**Comment by indutny** [comment]
Thank you, @igrigorik ! Submitted a question there. Will report back as soon as I'll hear anything from WG.

**Comment by indutny** [comment]
Please see follow up discussion on IETF WG: https://lists.w3.org/Archives/Public/ietf-http-wg/2015JulSep/0006.html
