### ISSUE TITLE
AssertionError [ERR_ASSERTION]: assert(index !== -1)

### ISSUE THREAD

**Issue by ggepenyan** [indutny/spdy-transport#62]
I'm using react js. I found this issue there, and they told I have to post it here.
The expression evaluated to a falsy value: assert(index !== -1)
at PriorityNode.removeChild (node_modules/spdy-transport/lib/spdy-transport/priority.js:74:3)
Please help me, I have to fix it as soon as possible.

**Comment by jacobheun** [comment]
See https://github.com/spdy-http2/spdy-transport/issues/47#issuecomment-436956755, you need to upgrade the version you're using, this is fixed in the latest version.
