### ISSUE TITLE
The returned stream is no longer a "duplex"

### ISSUE THREAD

**Issue by diasdavid** [indutny/spdy-transport#9]
I'm using [`duplex-passthrough`](https://www.npmjs.com/package/duplex-passthrough) to wrap the stream returned by a `.request()` call, so that I can buffer writes before the stream is ready and until I updated the spdy-transport version I had installed, the abstract-stream-muxer tests were passing, now, I get an error from duplex-passthrough, saying that the stream is not a `duplex` stream.

error:
```bash
assert.js:86
  throw new assert.AssertionError({
        ^
AssertionError: Can only wrap duplexes
    at DuplexPassThrough.wrapStream (/Users/david/Documents/Code/ipfs/node-impl/node-spdy-stream-muxer/node_modules/duplex-passthrough/dp.js:33:1)
    at /Users/david/Documents/Code/ipfs/node-impl/node-spdy-stream-muxer/src/index.js:39:10
    at /Users/david/Documents/Code/ipfs/node-impl/node-spdy-stream-muxer/node_modules/spdy-transport/lib/spdy-transport/connection.js:570:9
    at Object.callback (/Users/david/Documents/Code/ipfs/node-impl/node-spdy-stream-muxer/node_modules/spdy-transport/lib/spdy-transport/stream.js:484:5)
    at Framer.tickSync (/Users/david/Documents/Code/ipfs/node-impl/node-spdy-stream-muxer/node_modules/spdy-transport/lib/spdy-transport/protocol/base/scheduler.js:130:12)
    at Framer.tick (/Users/david/Documents/Code/ipfs/node-impl/node-spdy-stream-muxer/node_modules/spdy-transport/lib/spdy-transport/protocol/base/scheduler.js:108:13)
    at /Users/david/Documents/Code/ipfs/node-impl/node-spdy-stream-muxer/node_modules/spdy-transport/lib/spdy-transport/protocol/base/scheduler.js:102:10
    at process._tickCallback (node.js:355:11)
npm ERR! Test failed.  See above for more details.
```

Anything changed on the stream returned? 

(note to self: lock installs to specific hashes so I can tell which version I had installed)

**Comment by diasdavid** [comment]
with 1.0.0-rc6 works fine

**Comment by diasdavid** [comment]
1.0.0-rc7 is golden though :)

**Comment by indutny** [comment]
@diasdavid yeah, I'm using `readable-stream` everywhere now to have `.cork()`/.`uncork()` for v0.10 and provide general stream support for v0.8... Unfortunately, it comes with some `instanceof` problems.

I wonder if there might be a way to figure it out on `package.json`?

**Comment by diasdavid** [comment]
I'm not 100% sure if I understood your idea of figuring it out through the package.json, did you mean to do the 'assert' through the type of stream passed to duplex-passthrough through the package.json name?

I did a fork and removed the assert to go around this problem (https://github.com/diasdavid/duplex-passthrough)

**Comment by indutny** [comment]
No, I'm trying to figure out how I can use `readable-stream` on node v0.8 an v0.10, and `stream` everywhere else. Guess I should just use `if` branch.

**Comment by indutny** [comment]
Nope, thinking more about it - it sounds even more terrible. I guess that module should not be asserting on the instance after all.

**Comment by diasdavid** [comment]
Thank you for thinking through it, I also don't have any elegant solution for the problem. Assuming that we know which type of stream is being passed should be enough.
